import React from 'react';
export const Const = {
	path:'/',
	api:'http://localhost:8888/api',
	CREATE_FORM : "create_form",
	DELETE_FORM : "delete_form",
	GET_FORM:'GET_FORM',
	CREATE_WORKFLOW : "create_workflow",
	CREATE_FORMDETAIL : "create_detailform",
	GET_FORMDETAIL : "get_detailform",
	ADD_MODULE: 'ADD_MODULE',
	DELETE_MODULE: 'DELETE_MODULE',
	ADD_FORM: 'ADD_FORM',
	EDIT_FORM: 'EDIT_FORM',
	DELETE_FORM: 'DELETE_FORM',
	ADD_COMPONENT: 'ADD_COMPONENT',
	MOVE_COMPONENT:'MOVE_COMPONENT',
	DELETE_COMPONENT: 'DELETE_COMPONENT',
	EDIT_COMPONENT: 'EDIT_COMPONENT',
	ADD_COMPONENT_VIEWER: 'ADD_COMPONENT_VIEWER',
	DELETE_COMPONENT_VIEWER: 'DELETE_COMPONENT_VIEWER',
	EDIT_COMPONENT_VIEWER: 'EDIT_COMPONENT_VIEWER',
	ADD_COMPONENT_TAB:'ADD_COMPONENT_TAB'
};
