import React from 'react';
export const Const = {
	path:'/',
	api:'http://dev.nostratech.com:10093/',
	ADD_MODULE: 'ADD_MODULE',
	DELETE_MODULE: 'DELETE_MODULE',
	ADD_FORM: 'DELETE_MODULE',
	DELETE_FORM: 'DELETE_MODULE',
	EDIT_FORM: 'DELETE_MODULE',
	ADD_COMPONENT: 'ADD_COMPONENT',
	DELETE_COMPONENT: 'DELETE_COMPONENT'
};
